package htwsaar.ariadne.Backend.enums;

public enum Modules {
    BETRIEBSSYSTEMEINFUEHRUNG, BETRIEBSWIRTSCHAFTSLEHRE, ENGLISCH_EINS, INFORMATIK_EINS, MATHEMATIK_EINS, PROGRAMMIERUNG_EINS,
    ENGLISCH_ZWEI, INFORMATIK_ZWEI, MATHEMATIK_ZWEI, PROGRAMMERIUNG_ZWEI, RECHNERARCHITEKTUR, WIRTSCHAFTSINFORMATIK
}
